apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  annotations:
    scenarios.ai.sap.com/name: "scenario-alicloud-validation-I520234"
    executables.ai.sap.com/name: "executable-alicloud-validation-I520234"
    executables.ai.sap.com/description: "Workflow Template for Alicloud validation"
  labels:
    scenarios.ai.sap.com/id: "scenario-alicloud-validation-I520234"
    executables.ai.sap.com/id: "executable-alicloud-validation-I520234"
    ai.sap.com/version: 0.0.1
  name: "alicloudvalidationi520234.sot"
spec:
  entrypoint: alicloud-validation
  templates:
  - name: alicloud-validation
    metadata:
      labels:
        ai.sap.com/resourcePlan: starter
    outputs:
      artifacts:
      - name: alicloud-validation-output
        path: /app/model/
        globalName: alicloud-validation-output
        archive:
          none: {}
    container:
      image: alpine
      imagePullPolicy: Always
      command: ["/bin/sh", "-c"]
      args:
      - >
        set -e && echo "---Validation for Alicloud---" > /app/model/alicloud-validation-output && ls -la /app/data/ >> /app/model/alicloud-validation-output
